schemaVersion: 2.3.0
metadata:
  name: rhas-starter
  tags:
    - rhas
    - jumpstarter
    - aib
    - rhivos
    - autosd
components:
  #- name: runtime-pv
  #  volume:
  #    size: 2Gi
  - name: runtime
    container:
      image: ghcr.io/rhadp/rhas-starter:latest
      #volumeMounts:
      #  - name: runtime-pv
      #    path: "/home/user"
      memoryLimit: "4Gi"
      memoryRequest: "1Gi"
      cpuLimit: "4"
      cpuRequest: "1"
      mountSources: true
