schemaVersion: 2.3.0
metadata:
  name: rhas-starter
  tags:
    - rhas
    - jumpstarter
    - aib
    - rhivos
    - autosd
components:
  - name: workspace
    container:
      image: ghcr.io/rhadp/rhas-starter:latest
      memoryLimit: "4Gi"
      memoryRequest: "1Gi"
      cpuLimit: "4"
      cpuRequest: "1"
      mountSources: true
commands:
  - id: init-workspace
    exec:
      component: workspace
      commandLine: |
        /venv/bin/init-workspace
events:
  postStart:
    - init-workspace