FROM ghcr.io/rhadp/builder:latest

USER root

RUN dnf install -y epel-release && \
    dnf install -y \
        cmake \
        make \
        gcc \
        gcc-c++ \
        glibc-devel \
        socat \
        vsomeip3 \
        vsomeip3-devel \
        vsomeip3-routingmanager \
        boost-devel \
        boost-system \
        boost-thread \
        #boost-log \
        #boost-chrono \
        #boost-date-time \
        #boost-atomic \
        #boost-filesystem \
        #boost-regex \
        && dnf -y clean all --enablerepo='*' && \
        rm -rf /var/cache/dnf

RUN mkdir -p /tmp/log /run/dlt /run/vsomeip && \
    chown 1001:1001 /tmp/log && chmod -R 777 /tmp/log && \
    chown 1001:0 /run/dlt && chmod -R 777 /run/dlt && \
    chown 1001:0 /run/vsomeip && chmod -R 777 /run/vsomeip

# Reset permissions of modified directories
RUN rpm-file-permissions && chown -R 1001:0 ${APP_ROOT}

# back to the user
USER 1001