kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auto-builder-image-pusher
subjects:
  - kind: ServiceAccount
    name: image-pusher
    namespace: auto-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole