FROM quay.io/centos-sig-automotive/autosd:latest

ENV INSTALL_DIR=/usr/local/bin

COPY engine-service ${INSTALL_DIR}/
COPY entrypoint.sh ${INSTALL_DIR}/
COPY radio-service ${INSTALL_DIR}/
COPY radio-client ${INSTALL_DIR}/

# missing dirs
RUN mkdir -p /tmp/log && mkdir -p /run/dlt && mkdir -p /run/vsomeip

# permissions & ownership
RUN chmod +x ${INSTALL_DIR}/* && chown 1001:0 /usr/local/bin/* && \
  chown 1001:1001 /tmp/log && chmod -R 777 /tmp/log && \
  chown 1001:0 /run/dlt && chmod -R 777 /run/dlt && \
  chown 1001:0 /run/vsomeip && chmod -R 777 /run/vsomeip 

USER 1001

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]