FROM ghcr.io/rhadp/codespaces:latest

USER root
#--allowerasing
RUN dnf install -y epel-release && \
    dnf install -y \
        cmake \
        make \
        gcc \
        gcc-c++ \
        glibc-devel \
        socat \
        vsomeip3 \
        vsomeip3-devel \
        vsomeip3-routingmanager \
        boost-devel \
        boost-system \
        boost-thread \
        #boost-log \
        #boost-chrono \
        #boost-date-time \
        #boost-atomic \
        #boost-filesystem \
        #boost-regex \
        && dnf -y clean all --enablerepo='*' && \
        rm -rf /var/cache/dnf

RUN mkdir -p /tmp/log /run/dlt /run/vsomeip

# A last pass to make sure that an arbitrary user can write in $HOME
RUN chgrp -R 0 /home && chmod -R g=u /home

# back to the user
USER 10001