FROM ghcr.io/rhadp/codespaces:latest

USER root

# install this repository's version of jumpstarter
ENV JUMPSTARTER_VERSION=develop \
    JUMPSTARTER_REPO=https://github.com/mickume/jumpstarter

# install jumpstarter & other python dependencies
COPY requirements.txt /tmp/requirements.txt

RUN uv venv /venv && \
    uv pip install "git+${JUMPSTARTER_REPO}@${JUMPSTARTER_VERSION}#subdirectory=python/packages/jumpstarter-all" && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt && \
    echo "alias python='uv run python'" >> /home/user/.bashrc && \
    echo "alias pip='uv pip'" >> /home/user/.bashrc && \
    echo "source /venv/bin/activate" >> /home/user/.bashrc 

# A last pass to make sure that an arbitrary user can write in $HOME
RUN chgrp -R 0 /home && chmod -R g=u /home

# back to the user
USER 10001